// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hexarchy/itmo-calendar/internal/handlers/http/v1/models"
)

// HealthCheckOKCode is the HTTP code returned for type HealthCheckOK
const HealthCheckOKCode int = 200

/*
HealthCheckOK Service is healthy.

swagger:response healthCheckOK
*/
type HealthCheckOK struct {
}

// NewHealthCheckOK creates HealthCheckOK with default headers values
func NewHealthCheckOK() *HealthCheckOK {

	return &HealthCheckOK{}
}

// WriteResponse to the client
func (o *HealthCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// HealthCheckServiceUnavailableCode is the HTTP code returned for type HealthCheckServiceUnavailable
const HealthCheckServiceUnavailableCode int = 503

/*
HealthCheckServiceUnavailable Service is unhealthy.

swagger:response healthCheckServiceUnavailable
*/
type HealthCheckServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHealthCheckServiceUnavailable creates HealthCheckServiceUnavailable with default headers values
func NewHealthCheckServiceUnavailable() *HealthCheckServiceUnavailable {

	return &HealthCheckServiceUnavailable{}
}

// WithPayload adds the payload to the health check service unavailable response
func (o *HealthCheckServiceUnavailable) WithPayload(payload *models.Error) *HealthCheckServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health check service unavailable response
func (o *HealthCheckServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthCheckServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
