// Code generated by go-swagger; DO NOT EDIT.

package cal_dav

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hexarchy/itmo-calendar/internal/handlers/http/v1/models"
)

// GetICalOKCode is the HTTP code returned for type GetICalOK
const GetICalOKCode int = 200

/*
GetICalOK iCal file.

swagger:response getICalOK
*/
type GetICalOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetICalOK creates GetICalOK with default headers values
func NewGetICalOK() *GetICalOK {

	return &GetICalOK{}
}

// WithPayload adds the payload to the get i cal o k response
func (o *GetICalOK) WithPayload(payload io.ReadCloser) *GetICalOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get i cal o k response
func (o *GetICalOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetICalOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetICalNotFoundCode is the HTTP code returned for type GetICalNotFound
const GetICalNotFoundCode int = 404

/*
GetICalNotFound Not found.

swagger:response getICalNotFound
*/
type GetICalNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetICalNotFound creates GetICalNotFound with default headers values
func NewGetICalNotFound() *GetICalNotFound {

	return &GetICalNotFound{}
}

// WithPayload adds the payload to the get i cal not found response
func (o *GetICalNotFound) WithPayload(payload *models.Error) *GetICalNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get i cal not found response
func (o *GetICalNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetICalNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetICalInternalServerErrorCode is the HTTP code returned for type GetICalInternalServerError
const GetICalInternalServerErrorCode int = 500

/*
GetICalInternalServerError Internal server error.

swagger:response getICalInternalServerError
*/
type GetICalInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetICalInternalServerError creates GetICalInternalServerError with default headers values
func NewGetICalInternalServerError() *GetICalInternalServerError {

	return &GetICalInternalServerError{}
}

// WithPayload adds the payload to the get i cal internal server error response
func (o *GetICalInternalServerError) WithPayload(payload *models.Error) *GetICalInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get i cal internal server error response
func (o *GetICalInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetICalInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
