// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubscribeRequest subscribe request
//
// swagger:model SubscribeRequest
type SubscribeRequest struct {

	// isu
	// Example: 123456789
	// Required: true
	Isu *int64 `json:"isu"`

	// password
	// Example: user_password
	// Required: true
	Password *string `json:"password"`
}

// Validate validates this subscribe request
func (m *SubscribeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIsu(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubscribeRequest) validateIsu(formats strfmt.Registry) error {

	if err := validate.Required("isu", "body", m.Isu); err != nil {
		return err
	}

	return nil
}

func (m *SubscribeRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this subscribe request based on context it is used
func (m *SubscribeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubscribeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscribeRequest) UnmarshalBinary(b []byte) error {
	var res SubscribeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
